### ISSUE TITLE
"Something went wrong" error after fb login

### ISSUE THREAD

**Issue by ribagek** [nraboy/ng-cordova-facebook-example#19]
Hello!

I followed instruction and created .apk. Installed and app runs well. Then I click Oauth Sign In - it goes to fb login page. After I enter email/pass it says "Something went wrong" with link "Back to home". When I click that link I am redirected to my FB profile feed so login was successfull. And if go back to app screen and try to click Profile of Feed - alert appears saying that I'm not logged in.

What could be the cause of this?

**Comment by nraboy** [comment]
What do your application logs say?

**Comment by ribagek** [comment]
![adb](https://cloud.githubusercontent.com/assets/6089367/9905208/46c684bc-5c8c-11e5-996c-f2beb74d06e8.png)
Here the logs. I suppose the error I marked red can be the cause but don't know what does it mean.

**Comment by nraboy** [comment]
I just downloaded the repository, built it, and tested it myself.  I received no problems which leads me to believe you have an incorrect setup in your Facebook dashboard.

**Comment by ribagek** [comment]
the problem is that default available items to retreive in fresh FB app are email, public_profile, user_friends. But in this example the code requires to have: "email", "read_stream", "user_website", "user_location", "user_relationships". And I need only login functionality so didn't request any other items except default. And that was the cause of error.

**Comment by nraboy** [comment]
Fair enough.  Glad you resolved it :-)

**Comment by sadid-khan** [comment]
```
<head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <script src="js/angular.js"></script>
    <script src="js/ngCordova/ng-cordova.js"></script>
    <script type="text/javascript" src="cordova.js"></script>
    <title>Hello World</title>
    <script src="js/app.js"></script>
</head>
<body data-ng-app="myApp">
   <div ng-controller="OAuthCtrl">
       <label >
           <button class="button button-block button-positive" ng-click="facebookLogin()">
               Login with Facebook
           </button>
       </label>
   </div>
</body>
```

and the app.js part:

var app = angular.module('myApp', ['ngCordova']);
app.controller("OAuthCtrl", function($scope, $cordovaOauth)
{
    $scope.facebookLogin = function() {
        alert("inside method");
        $cordovaOauth.facebook("757621711015442", ["email","public_profile", "user_friends"]).then(function(result) 
{
            alert("sadid");
            alert(result.data);
            // results
        }, function(error) {
            alert("error");
            alert(error);
            // error
        });
    }

in facebook, i just created the app .
![image](https://cloud.githubusercontent.com/assets/14312473/9926360/a2bd1646-5d36-11e5-933f-2e0030624e25.png)

then settings-> advanced->Client OAuth Settings 
![capture](https://cloud.githubusercontent.com/assets/14312473/9926446/45dea3ee-5d37-11e5-9083-d436a8f02807.PNG)

then what i am missing...??

**Comment by ribagek** [comment]
Then go Settings. Enter localhost in domains field. Create new platform website and paste there in the field http://localhost/callback. Then in the codeof app.js  find line with "email", "read_stream", "user_website", "user_location", "user_relationships" and remove all except email.

**Comment by sadid-khan** [comment]
did everything u told.. but nothing happened
how to make app live...?

**Comment by ribagek** [comment]
Do you test on real device? If so then all requirements seem satisfied. In that case you need to check logs.

**Comment by sadid-khan** [comment]
i had some settings problem of facebook app. that problem was solved and i am able to get access_token from fb.

but now i am facing a different issue. i am using ngcordova Facebook Plugin for the same facebook app i worked with OAuth plugin.

but now i am getting error "given url is not allowed by the application configuration. one or more url of the given urls is not allowed by the app's settings.to use this url you must add a valid native platform in your app's settings in ngcordova android"

here i am posting log.. my log is filtured.
09-22 05:37:43.703  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{2fd659fd token=android.os.BinderProxy@245852c1 {io.cordova.hellocordova/com.facebook.LoginActivity}} show : false
09-22 05:37:49.853  17684-18633/io.cordova.hellocordova I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
09-22 05:39:21.263  17684-17684/io.cordova.hellocordova W/ResourceType﹕ Failure getting entry for 0x01080ad0 (t=7 e=2768) (error -75)
09-22 05:39:21.283  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ installDecor mIsFloating : false
09-22 05:39:21.283  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ installDecor flags : 8454400
09-22 05:39:21.323  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{4a2093c token=android.os.BinderProxy@1d402199 {io.cordova.hellocordova/io.cordova.hellocordova.MainActivity}} show : true
09-22 05:39:21.413  17684-17684/io.cordova.hellocordova D/CordovaInterfaceImpl﹕ Sending activity result to plugin
09-22 05:39:21.413  17684-17684/io.cordova.hellocordova D/ConnectPlugin﹕ activity result in plugin: requestCode(64206), resultCode(0)
09-22 05:39:21.423  17684-17684/io.cordova.hellocordova D/ConnectPlugin﹕ onSessionStateChange:CLOSED_LOGIN_FAILED
09-22 05:39:21.423  17684-17684/io.cordova.hellocordova E/ConnectPlugin﹕ exception:com.facebook.FacebookOperationCanceledException: Operation canceled
09-22 05:39:21.423  17684-17684/io.cordova.hellocordova E/ConnectPlugin﹕ com.facebook.FacebookOperationCanceledException: Operation canceled
09-22 05:39:21.423  17684-17684/io.cordova.hellocordova I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1d402199 time:18896677
09-22 05:39:21.493  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(79)] "inside login error", source: file:///android_asset/www/js/app.js (79)
09-22 05:39:21.493  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(114)] "errorCode=4201", source: file:///android_asset/www/js/app.js (114)
09-22 05:39:21.493  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(114)] "errorMessage=User cancelled dialog", source: file:///android_asset/www/js/app.js (114)
09-22 05:39:33.923  17684-17684/io.cordova.hellocordova D/ViewRootImpl﹕ ViewPostImeInputStage ACTION_DOWN
09-22 05:39:34.063  17684-17752/io.cordova.hellocordova D/ConnectPlugin﹕ login FB
09-22 05:39:34.073  17684-17684/io.cordova.hellocordova D/ConnectPlugin﹕ onSessionStateChange:OPENING
09-22 05:39:34.093  17684-17752/io.cordova.hellocordova I/Timeline﹕ Timeline: Activity_launch_request id:io.cordova.hellocordova time:18909349
09-22 05:39:34.153  17684-17752/io.cordova.hellocordova W/PluginManager﹕ THREAD WARNING: exec() call to FacebookConnectPlugin.login blocked the main thread for 91ms. Plugin should use CordovaInterface.getThreadPool().
09-22 05:39:34.163  17684-17684/io.cordova.hellocordova W/ResourceType﹕ Failure getting entry for 0x01080ad0 (t=7 e=2768) (error -75)
09-22 05:39:34.173  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ installDecor mIsFloating : false
09-22 05:39:34.173  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ installDecor flags : 8454400
09-22 05:39:34.203  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ isFloatingMenuEnabled mFloatingMenuBtn : null
09-22 05:39:34.203  17684-17684/io.cordova.hellocordova D/PhoneWindow﹕ _FMB_ isFloatingMenuEnabled return false
09-22 05:39:34.243  17684-17684/io.cordova.hellocordova I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@2c7dcf7a time:18909495
09-22 05:39:34.243  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{4a2093c token=android.os.BinderProxy@1d402199 {io.cordova.hellocordova/io.cordova.hellocordova.MainActivity}} show : true
09-22 05:39:34.593  17684-17684/io.cordova.hellocordova I/Timeline﹕ Timeline: Activity_launch_request id:com.facebook.katana time:18909848
09-22 05:39:34.753  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{4a2093c token=android.os.BinderProxy@1d402199 {io.cordova.hellocordova/io.cordova.hellocordova.MainActivity}} show : false
09-22 05:39:34.833  17684-18633/io.cordova.hellocordova I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
09-22 05:39:34.953  17684-18633/io.cordova.hellocordova I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-22 05:39:35.313  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{4dc1fff token=android.os.BinderProxy@2c7dcf7a {io.cordova.hellocordova/com.facebook.LoginActivity}} show : false
09-22 05:39:42.063  17684-17684/io.cordova.hellocordova V/ActivityThread﹕ updateVisibility : ActivityRecord{4a2093c token=android.os.BinderProxy@1d402199 {io.cordova.hellocordova/io.cordova.hellocordova.MainActivity}} show : true
09-22 05:39:42.123  17684-17684/io.cordova.hellocordova D/CordovaInterfaceImpl﹕ Sending activity result to plugin
09-22 05:39:42.123  17684-17684/io.cordova.hellocordova D/ConnectPlugin﹕ activity result in plugin: requestCode(64206), resultCode(0)
09-22 05:39:42.163  17684-17684/io.cordova.hellocordova D/ConnectPlugin﹕ onSessionStateChange:CLOSED_LOGIN_FAILED
09-22 05:39:42.163  17684-17684/io.cordova.hellocordova E/ConnectPlugin﹕ exception:com.facebook.FacebookOperationCanceledException: Operation canceled
09-22 05:39:42.163  17684-17684/io.cordova.hellocordova E/ConnectPlugin﹕ com.facebook.FacebookOperationCanceledException: Operation canceled
09-22 05:39:42.163  17684-17684/io.cordova.hellocordova I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1d402199 time:18917414
09-22 05:39:42.173  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(79)] "inside login error", source: file:///android_asset/www/js/app.js (79)
09-22 05:39:42.173  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(114)] "errorCode=4201", source: file:///android_asset/www/js/app.js (114)
09-22 05:39:42.173  17684-17684/io.cordova.hellocordova I/chromium﹕ [INFO:CONSOLE(114)] "errorMessage=User cancelled dialog", source: file:///android_asset/www/js/app.js (114)
09-22 05:39:49.833  17684-18633/io.cordova.hellocordova I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false

**Comment by nraboy** [comment]
The Facebook plugin is not compatible with cordovaOauth to my knowledge.  Use either or, but not both.

If you choose to use cordovaOauth, I encourage you to look at Facebook's RESTful API documentation for working with their API such as updating the profile.

Regards,

**Comment by sadid-khan** [comment]
i am doing this for learning. i will not use both at a time..

cordova oauth is working fine.
my problem is i get error when i use facebook plugin of ng-cordova. the error is mentioned below - 

"given url is not allowed by the application configuration. one or more url of the given urls is not allowed by the app's settings.to use this url you must add a valid native platform in your app's settings in ngcordova android"

i think the problem is in the settings not in the plugin.. what settings should i have in the fb app (suppose "TestApp" ) to use facebook plugin of ng-cordova. 

my fb app is working with ngcordova OAuth plugin. but when i use facebook plugin, after login it shows this

![screenshot_2015-09-23-00-32-05](https://cloud.githubusercontent.com/assets/14312473/10037898/b0d35f9e-618a-11e5-8d41-da3ab2fadd09.png)

**Comment by nraboy** [comment]
Yes, and I'm telling you I know nothing about the Facebook plugin of ng-cordova.  These are two very different plugins.  I only support ng-cordova-oauth.

You'll have to post in the forums if you want help with the other plugin.

Sorry,
