### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by rrubio** [nraboy/ng-cordova-facebook-example#20]
Hi Guys,

How would i go about refreshing the token with ng-cordova? this is so the user doesn't have to re-login each time token times out.

Cheers in advance.

**Comment by nraboy** [comment]
Oauth tokens should never be refreshable in a client facing application.  Because of this, ng-cordova-oauth uses the implicit grant type defined in the Oauth spec as being unable to request refresh tokens to refresh an access token.

I'd recommend configuring your own web server and have it manage explicit grant types for refreshing tokens for your application.

Best,

**Comment by rrubio** [comment]
Cheers mate, makes sense.
